const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let s={speed:0,dir:0,currentHeading:287,desiredHeading:287,steer:0,anchor:false,hold:false,cruise:false,transition:false};
const ring=$("#steerRing"),knob=$("#steerKnob"),thrust=$("#thrustRing");
for(let n=0;n<40;n++){let d=document.createElement("i");d.className="thrustDot";d.style.transform="rotate("+n*9+"deg) translateY(-"+(($("#helm").clientWidth/2)-20)+"px)";thrust.appendChild(d)}
function angleTransform(el,a,r){el.style.transform="translateX(-50%) rotate("+a+"deg)";el.style.transformOrigin="50% "+r+"px"}
function render(){ $("#speedVal").textContent=Math.round(s.speed)+"%";$("#speed").value=s.speed;$("#sog").textContent=(s.speed*.048).toFixed(1);$("#heading").textContent=Math.round((s.currentHeading+360)%360)+"°";$("#anchor").classList.toggle("on",s.anchor);$("#hold").classList.toggle("on",s.hold);$("#cruise").classList.toggle("on",s.cruise);$("#direction").textContent=s.transition?"REVERSING…":s.dir>0?"FORWARD":s.dir<0?"REVERSE":"NEUTRAL";$("#direction").className="direction "+(s.dir>0?"forwardDir":s.dir<0?"reverseDir":"");$$(".thrustDot").forEach((d,i)=>d.classList.toggle("on",i<Math.round(s.speed/2.5)));angleTransform(knob,s.steer,$("#helm").clientWidth/2+8);angleTransform($("#headingMarker"),s.steer,$("#helm").clientWidth/2-10);let a=s.speed*.52;$("#amps").textContent=a.toFixed(1)+" A";$("#watts").textContent=Math.round(a*37.8)+" W";$("#runtime").textContent=a>1?(76/a).toFixed(1)+" h":"--"}
function page(id){$$(".screen").forEach(x=>x.classList.add("hidden"));$("#"+id).classList.remove("hidden");$$("nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===id));scrollTo(0,0)}
function setSteer(v){s.steer=((v+180)%360+360)%360-180;s.desiredHeading=(s.currentHeading+s.steer+360)%360;render()}
$("#left").onclick=()=>setSteer(s.steer-10);$("#right").onclick=()=>setSteer(s.steer+10);$("#center").onclick=()=>setSteer(0);
function dial(e){const r=ring.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2);setSteer(Math.atan2(x,-y)*180/Math.PI)}
knob.addEventListener("pointerdown",e=>{knob.setPointerCapture(e.pointerId);dial(e)});knob.addEventListener("pointermove",e=>{if(knob.hasPointerCapture(e.pointerId))dial(e)});
function forward(){if(s.transition)return;if(s.dir<0){s.speed=0;s.dir=1}else{s.dir=1;s.speed=Math.min(100,s.speed+10)}render()}
async function reverse(){if(s.transition)return;if(s.dir>0&&s.speed>0){s.transition=true;let start=s.speed,steps=50;for(let i=1;i<=steps;i++){await new Promise(r=>setTimeout(r,100));s.speed=start*(1-i/steps);render()}s.speed=0;s.steer=180;s.desiredHeading=(s.currentHeading+180)%360;render();await new Promise(r=>setTimeout(r,500));s.dir=-1;s.speed=10;s.transition=false;render()}else{s.dir=-1;s.speed=Math.min(100,(s.speed||0)+10);render()}}
$("#forward").onclick=forward;$("#reverse").onclick=reverse;$("#speed").oninput=e=>{s.speed=+e.target.value;if(!s.speed)s.dir=0;render()};
$("#anchor").onclick=()=>{s.anchor=!s.anchor;if(s.anchor)s.cruise=false;render()};$("#hold").onclick=()=>{s.hold=!s.hold;render()};$("#cruise").onclick=()=>{s.cruise=!s.cruise;if(s.cruise)s.anchor=false;render()};$("#stop").onclick=()=>{s.speed=0;s.dir=0;s.anchor=false;s.cruise=false;s.transition=false;render()};
$("#batteryCard").onclick=()=>page("batteryPage");$$(".back").forEach(x=>x.onclick=()=>page("controlPage"));$$("nav button").forEach(x=>x.onclick=()=>page(x.dataset.page));$("#settingsBtn").onclick=()=>page("settingsPage");$("#menu").onclick=()=>page("settingsPage");
let held=false,timer=null;$$(".helpable").forEach(el=>{const start=()=>{held=false;timer=setTimeout(()=>{held=true;const [t,...rest]=(el.dataset.help||"Help|No description available.").split("|");$("#helpTitle").textContent=t;$("#helpText").textContent=rest.join("|");$("#helpOverlay").classList.remove("hidden")},600)},end=e=>{clearTimeout(timer);if(held){e.preventDefault();e.stopPropagation();held=false}};el.addEventListener("pointerdown",start);el.addEventListener("pointerup",end,true);el.addEventListener("pointercancel",()=>clearTimeout(timer));el.addEventListener("contextmenu",e=>e.preventDefault())});$("#helpClose").onclick=()=>$("#helpOverlay").classList.add("hidden");$("#helpOverlay").onclick=e=>{if(e.target===$("#helpOverlay"))$("#helpOverlay").classList.add("hidden")};if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");render();